#This is a general configuration, for Game specific settings open the games folder

#SQL database settings
sql:
  #Set this as false if you want to use a flat-file instead.
  use-mysql: false
  database: "titansbattle"
  mysql:
    hostname: "localhost"
    port: 3306
    username: "titansbattle"
    password: ""

#Language used in plugin's message
language: en

#Send more output to the console?
debug: false

#Change the commands
commands:
  titansbattle: "titansbattle"
  create: "create"
  join: "join"
  kick: "kick"
  exit: "exit"
  start: "start"
  cancel: "cancel"
  setdestination: "setdestination"
  setinventory: "setinventory"
  setkit: "setkit"
  setprize: "setprize"
  help: "help"
  reload: "reload"
  watch: "watch"
  winners: "winners"
  ranking: "ranking"
  edit: "edit"
  prize: "prize"
  game: "game"
  members: "members"
  leaders: "leaders"
  killer: "killer"
  groups: "groups"
  players: "players"
  challenge: "challenge"
  group: "group"
  player: "player"
  accept: "accept"
  deny: "deny"
  info: "info"
  setwinner: "setwinner"
  config: "config"
  x1clan: "x1clan"
  spec: "spec"
  getkit: "getkit"
  teleport: "teleport"

#Sounds used in games, to disable one leave it ""
sounds:
  join_game: "ENTITY_PLAYER_LEVELUP"
  leave_game: "BLOCK_ANVIL_BREAK"
  watch: "ENTITY_ENDERMAN_TELEPORT"
  teleport: "ENTITY_ENDERMAN_TELEPORT"
  victory: "UI_TOAST_CHALLENGE_COMPLETE"
  enemy_death: "ENTITY_WOLF_GROWL"
  ally_death: "ENTITY_WOLF_HOWL"
  border: "ENTITY_GHAST_SCREAM"

#Date format used on /tb winners command
date-format: "dd/MM/yyyy"

#Set how many lines should be displayed on those commands
page-limit:
  help: 7
  ranking: 10

#List here commands that the plugin will not block in battle phase
allowed_commands: [ "/tb exit", "/tb winners" ]

#List here commands that the plugin will not block in spectator phase
allowed_commands_in_spectator: [ "/tb watchroom", "/tb watch", "/tb spec" ]

#Commands that NO ONE will be able to use, not even players who didn't join the game
blocked_commands_everyone:
  - "/clan disband"
  - "/f disband"
  - "/clan kick"
  - "/f kick"
  - "/marry tp"

viaversion:
  block-protocols: [ ]

#Send a webhook in game start, leave empty to disable
discord_webhook_url: ""

#Destinations
destinations:
  general_exit:

#Will the game begin automatically? Which game? When?
#Game: the name of the game file
#Frequency: HOURLY, DAILY, WEEKLY, MONTHLY
#Day: the day of the week (1 = Monday), or the day of the month
#Hour format: 0 to 24
#Minute format: 0 to 59
#If you want more events, just follow the example below, copy them and change the number
scheduler:
  enabled: true
  events:
    1:
      game: gladiador
      frequency: DAILY
      hour: 18
      minute: 30
    2:
      game: gladiador
      frequency: HOURLY
      minute: 30
    3:
      game: gladiador
      frequency: WEEKLY
      day: 1
      hour: 18
      minute: 30
    4:
      game: gladiador
      frequency: MONTHLY
      day: 15
      hour: 18
      minute: 30

#NPC Proxy System Configuration
battle:
  npcProxy:
    enabled: true
    provider: auto  # auto | fancynpcs | citizens | vanilla
    # Disconnection limits and timeout settings
    maxDisconnections: 3  # Maximum times a player can disconnect during the same event
    maxOfflineTimeMs: 300000  # Maximum time a player can stay offline (5 minutes)
    vanilla:
      mobType: ZOMBIE  # Entity type for vanilla proxy mobs
    # Reason for not spawning a proxy NPC
    bypass-reasons:
      - "banned"

#Data used by the plugin, don't edit it.
data:
  respawn: [ ]
  clear_inv: [ ]