main: "me.roinujnosde.titansbattle.TitansBattle"
name: "TitansBattle"
author: "RoinujNosde"
version: "${project.version}-${git.commit.id.describe-short}"
api-version: 1.13
softdepend:
  - "SimpleClans"
  - "Factions"
  - "mcMMO"
  - "PlaceholderAPI"
  - "Essentials"
  - "Multiverse-Core"
permissions:
  titansbattle.admin:
    description: "Gives access to administrator commands"
    default: op
    children:
      titansbattle.cancel: true
      titansbattle.challenge.player: false
      titansbattle.command-bypass: true
      titansbattle.create: true
      titansbattle.kick: true
      titansbattle.player: true
      titansbattle.ranking: true
      titansbattle.reload: true
      titansbattle.setdestination: true
      titansbattle.setinventory: true
      titansbattle.setwinner: true
      titansbattle.start: true
      titansbattle.winners: true
  titansbattle.player:
    description: "Gives access to player commands"
    default: false
    children:
      titansbattle.challenge.accept: true
      titansbattle.challenge.exit: true
      titansbattle.challenge.group: true
      titansbattle.challenge.watch: true
      titansbattle.exit: true
      titansbattle.help: true
      titansbattle.join: true
      titansbattle.watchroom: true
  titansbattle.challenge.accept:
    default: false
  titansbattle.challenge.player:
    default: false
  titansbattle.challenge.group:
    default: false
  titansbattle.challenge.watch:
    default: false
  titansbattle.challenge.exit:
    default: false
  titansbattle.join:
    default: false
  titansbattle.exit:
    default: false
  titansbattle.watchroom:
    default: false
  titansbattle.help:
    default: false
  titansbattle.create:
    default: false
  titansbattle.reload:
    default: false
  titansbattle.cancel:
    default: false
  titansbattle.start:
    default: false
  titansbattle.kick:
    default: false
    description: Allows kicking players from games
  titansbattle.setdestination:
    default: false
  titansbattle.command-bypass:
    default: false
    description: Bypasses command restrictions in games
  titansbattle.winners:
    default: false
  titansbattle.setinventory:
    default: false
  titansbattle.ranking:
    default: false
  titansbattle.setwinner:
    default: false
